
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qureshi Home
 */
import java.sql.*;
public class editCat extends javax.swing.JFrame {
int refresh =0;
ResultSet rs=null;
ResultSet English=null;
ResultSet Math=null;
ResultSet Computer=null;
ResultSet General=null;
ResultSet Common=null;
DAO d = new DAO();
variable v = new variable();
    /**
     * Creates new form editCat
     */
 public editCat() {
       
        initComponents();
        updcat.setVisible(false);
        s.setVisible(false);
        n.setVisible(false);
        p.setVisible(false);
        member_id.disable();
        
    }
    public editCat(variable v) {
         this.v.role=v.role;
        initComponents();
        if(!"Admin".equals(this.v.role)){
        updcat.setVisible(false);
        s.setVisible(false);
        n.setVisible(false);
        p.setVisible(false);
        member_id.disable();
        member_id.setText(v.member_id);
        s.doClick();
        }else{
            startQuiz.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        x4 = new javax.swing.JLabel();
        minimize2 = new javax.swing.JLabel();
        s = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        member_id = new javax.swing.JTextField();
        updcat = new javax.swing.JButton();
        n = new javax.swing.JButton();
        p = new javax.swing.JButton();
        cat1 = new javax.swing.JRadioButton();
        cat2 = new javax.swing.JRadioButton();
        cat3 = new javax.swing.JRadioButton();
        cat4 = new javax.swing.JRadioButton();
        cat5 = new javax.swing.JRadioButton();
        startQuiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category");

        x4.setBackground(new java.awt.Color(153, 0, 0));
        x4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        x4.setForeground(new java.awt.Color(255, 255, 255));
        x4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x4.setText("X");
        x4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x4.setOpaque(true);
        x4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x4MouseClicked(evt);
            }
        });

        minimize2.setBackground(new java.awt.Color(0, 0, 0));
        minimize2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        minimize2.setForeground(new java.awt.Color(255, 255, 255));
        minimize2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize2.setText("_");
        minimize2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        minimize2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        minimize2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize2.setOpaque(true);
        minimize2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize2MouseClicked(evt);
            }
        });

        s.setText("Search");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student ID");

        member_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_idActionPerformed(evt);
            }
        });

        updcat.setText("Update Category");
        updcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updcatActionPerformed(evt);
            }
        });

        n.setText("Next");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        p.setText("Prev");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        cat1.setBackground(new java.awt.Color(0, 0, 0));
        cat1.setForeground(new java.awt.Color(255, 255, 255));
        cat1.setText("English");

        cat2.setBackground(new java.awt.Color(0, 0, 0));
        cat2.setForeground(new java.awt.Color(255, 255, 255));
        cat2.setText("Math");

        cat3.setBackground(new java.awt.Color(0, 0, 0));
        cat3.setForeground(new java.awt.Color(255, 255, 255));
        cat3.setText("Computer");

        cat4.setBackground(new java.awt.Color(0, 0, 0));
        cat4.setForeground(new java.awt.Color(255, 255, 255));
        cat4.setText("General Knowledge");

        cat5.setBackground(new java.awt.Color(0, 0, 0));
        cat5.setForeground(new java.awt.Color(255, 255, 255));
        cat5.setText("Common Sense ");

        startQuiz.setText("Start Quiz");
        startQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(member_id, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cat4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cat5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(s)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(n)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(minimize2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(updcat)
                .addGap(18, 18, 18)
                .addComponent(startQuiz)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(x4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimize2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(member_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s)
                    .addComponent(n)
                    .addComponent(p))
                .addGap(18, 18, 18)
                .addComponent(cat1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cat2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cat3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cat4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cat5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updcat)
                    .addComponent(startQuiz))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
       DAO d = new DAO();
               
       try{
            if(refresh==0){
                refresh=1;
                rs=d.selectCat();
                rs.next();
                }
           if(rs.previous()){
              member_id.setText(rs.getString(1));
           cat1.setSelected(false);
            cat2.setSelected(false);
            cat3.setSelected(false);
            cat4.setSelected(false);
            cat5.setSelected(false);
           if("1".equals(rs.getString(2))){
               cat1.setSelected(true);
           }
           if("1".equals(rs.getString(3))){
               cat2.setSelected(true);
           }
           if("1".equals(rs.getString(4))){
               cat3.setSelected(true);
           }
           if("1".equals(rs.getString(5))){
               cat4.setSelected(true);
           }
           if("1".equals(rs.getString(6))){
               cat5.setSelected(true);
           }
               
          }
           else{
               rs.next();
           }
       }catch(Exception ex){
           
       }
  
    }//GEN-LAST:event_pActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
       DAO d = new DAO();
                
       try{
           if(refresh==0){
               refresh=1;
                rs=d.selectCat();
                rs.previous();
                }
           if(rs.next()){
               member_id.setText(rs.getString(1));
           cat1.setSelected(false);
            cat2.setSelected(false);
            cat3.setSelected(false);
            cat4.setSelected(false);
            cat5.setSelected(false);
           if("1".equals(rs.getString(2))){
               cat1.setSelected(true);
           }
           if("1".equals(rs.getString(3))){
               cat2.setSelected(true);
           }
           if("1".equals(rs.getString(4))){
               cat3.setSelected(true);
           }
           if("1".equals(rs.getString(5))){
               cat4.setSelected(true);
           }
           if("1".equals(rs.getString(6))){
               cat5.setSelected(true);
           }
               
          }else{
               rs.previous();
           }
       }catch(Exception ex){
           
       }
    }//GEN-LAST:event_nActionPerformed

    private void updcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updcatActionPerformed
       refresh=0;
       int count=0;
       variable v = new variable();
       if(cat1.isSelected()){
           count++;
       }
       if(cat2.isSelected()){
           count++;
       }
       if(cat3.isSelected()){
           count++;
       }
       if(cat4.isSelected()){
           count++;
       }
       if(cat5.isSelected()){
           count++;
       }
       if(count==3 || count ==0){
           
           if(cat1.isSelected()){
           v.cat1="1";
       }
       if(cat2.isSelected()){
          v.cat2="1";
       }
       if(cat3.isSelected()){
           v.cat3="1";
       }
       if(cat4.isSelected()){
           v.cat4="1";
       }
       if(cat5.isSelected()){
          v.cat5="1";
       }
       v.member_id=member_id.getText();
       DAO d = new DAO();
       d.updateCat(v);   
       }else
       {
           JOptionPane.showMessageDialog(null,"Must Select none or Three Categories");
       }
            
    }//GEN-LAST:event_updcatActionPerformed

    private void member_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_idActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
         variable v = new variable();
        v.member_id=member_id.getText();
        if("".equals(v.member_id)){
            JOptionPane.showMessageDialog(null, "Please Enter Student ID to Search");
        }else{
        DAO d = new DAO();
        ResultSet rs=d.selectCatid(v);
        try{
            cat1.setSelected(false);
            cat2.setSelected(false);
            cat3.setSelected(false);
            cat4.setSelected(false);
            cat5.setSelected(false);
           if("1".equals(rs.getString(2))){
               cat1.setSelected(true);
           }
           if("1".equals(rs.getString(3))){
               cat2.setSelected(true);
           }
           if("1".equals(rs.getString(4))){
               cat3.setSelected(true);
           }
           if("1".equals(rs.getString(5))){
               cat4.setSelected(true);
           }
           if("1".equals(rs.getString(6))){
               cat5.setSelected(true);
           }
           

        }catch(Exception ex){
           
        }
        }
    }//GEN-LAST:event_sActionPerformed

    private void minimize2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize2MouseClicked
        this.setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize2MouseClicked

    private void x4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x4MouseClicked
        this.dispose();
    }//GEN-LAST:event_x4MouseClicked

    private void startQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startQuizActionPerformed
       refresh=0;
       int count=0;
      
       if(cat1.isSelected()){
           count++;
       }
       if(cat2.isSelected()){
           count++;
       }
       if(cat3.isSelected()){
           count++;
       }
       if(cat4.isSelected()){
           count++;
       }
       if(cat5.isSelected()){
           count++;
       }
       if(count==3){
           
           if(cat1.isSelected()){
           v.cat1="1";
       v.q_cat="Math";
       v.cat_name1="Computer";
       v.cat_name2="Math";
       v.cat_name3="English";
       
        English=d.pickPaper(v);
        QuestionPaper q =new QuestionPaper(v,English);
        q.setVisible(true);
        
       
       
       
       }
       if(cat2.isSelected()){
          v.cat2="1";
          v.q_cat="Math";
          English=d.pickPaper(v);
       }
       if(cat3.isSelected()){
           v.cat3="1";
           v.q_cat="Computer";
       }
       if(cat4.isSelected()){
           v.cat4="1";
           v.q_cat="General Knowledge";
       }
       if(cat5.isSelected()){
          v.cat5="1";
          v.q_cat="Common Sense";
       }
       v.member_id=member_id.getText();
       DAO d = new DAO();
       d.updateCat(v); 
       
    
       
       }else
       {
           JOptionPane.showMessageDialog(null,"Must Select Three Categories");
       }
            
    
    }//GEN-LAST:event_startQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new editCat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cat1;
    private javax.swing.JRadioButton cat2;
    private javax.swing.JRadioButton cat3;
    private javax.swing.JRadioButton cat4;
    private javax.swing.JRadioButton cat5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField member_id;
    private javax.swing.JLabel minimize2;
    private javax.swing.JButton n;
    private javax.swing.JButton p;
    private javax.swing.JButton s;
    private javax.swing.JButton startQuiz;
    private javax.swing.JButton updcat;
    private javax.swing.JLabel x4;
    // End of variables declaration//GEN-END:variables
}
